<?php $this->layout('../layouts/layout', ['title' => 'ventasMVC']) ?>
<?php $this->start('contenido') ?>
<div class="container">
  <h1>Categorias</h1>
  <div class="row">
    <div class="col-sm-4">
      <a class="btn btn-primary btn-block" is-modal="true" href="<?= URL . 'categoria/detail' ?>" data-toggle="modal" >Nuevo</a>
    </div>
    <div class="form-group">
      <div class="custom-control custom-switch custom-switch-off-danger custom-switch-on-success">
        <input type="checkbox" class="custom-control-input" name='Estado' id="chkEstado" checked>
        <label class="custom-control-label estado" for="chkEstado" style="cursor: pointer;">Estado</label>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-sm-12">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Descripcion</th>
            <th></th>
          </tr>
        </thead>
        <tbody id="tbCategoria">
          <?php foreach ($data as $category) : ?>
            <tr>
              <td><?= $this->e($category->IdCateg) ?></td>
              <td><?= $this->e($category->Nombre) ?></td>
              <td><?= $this->e($category->Descripcion) ?></td>
              <td>
                <a class="btn btn-info" title="Editar" is-modal="true" title="Modificar" data-toggle="modal" data-target="#exampleModal">
                  <i class="fa fa-pencil"></i>
                </a>
                <a class="btn btn-danger" data-id="<?= $this->e($category->IdCateg) ?>" title="Editar" href="<?= URL . "categoria/delete/" . $this->e($category->ID) ?>" title="Eliminar">
                  <i class="fa fa-trash"></i>
                </a>
              </td>
            </tr>
          <?php endforeach ?>
        </tbody>
      </table>
    </div>
  </div>
  <div class="modal fade" id="exampleModal" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Agregar Categoria</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="container-fluid">

            <form action="" id="form" method="post">
              <input type="hidden" name="id" id="ID" value="0" />
              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group">
                    <label for="id_nombre">Nombre:</label>
                    <input type="text" class="form-control" name="nombre" id="nombre" required value="">
                  </div>
                </div>
                <div class="col-sm-12">
                  <div class="form-group">
                    <label for="id_descripcion">Descripcion</label>
                    <input name="descripcion" id="descripcion" cols="30" rows="10" required value=""></input>
                  </div>
                </div>
                <div class="col-sm-12">
                  <div class=" form-group">
                    <input type="checkbox" class="form-check-input" id="chkEstadoOption" name="Estado">
                    <label class="form-check-label" for="exampleCheck1">Estado</label>
                  </div>
                </div>
              </div>
              <div class="modal-footer">

                <div class="col-sm-8">
                  <div class="form-group">
                    <button class="btn btn-primary btn-block" type="submit">Guardar</button>
                  </div>
                </div>
                <div class="col-sm-4">
                  <div class="form-group">
                    <button class="btn btn-danger btn-block" id="mCerrar" data-dismiss="modal">Cancelar</button>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>
<?php $this->stop() ?>

<?php $this->start('Modal') ?>

<?php
$title = "Categoria";
$size = MEDIANO;
include MAINPATH . "app/views/layouts/partials/_modalGenerico.phtml";
?>
<?php $this->stop() ?>

<?php $this->push('scripts'); ?>
<script src="<?= URL . 'js/categoria/index.js' ?>"></script>
<script src="<?= URL . 'js/categoria/modalCrud.js' ?>"></script>

<?php $this->end(); ?>