<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  <link rel="stylesheet" href="http://ventasmvc.test/public/css/test/suma.css">
  <title>Suma</title>
</head>

<body>
  <div class="container">
    <div class="row">
      <h1>Suma</h1>
      <div class="col-sm-4">
        <form action="<?= URL ?>test/suma" method="POST">
          <div class="mb-3">
            <label for="num1" class="form-label">Numero 1</label>
            <input type="number" name="num1" class="form-control" value="<?= $num1 ?>" step="1" >
          </div>
          <div class="mb-3">
            <label for="num2" class="form-label">Numero 2</label>
            <input type="number" name="num2" class="form-control" value="<?= $num2 ?>" step="1" >
          </div>
          <button type="submit" class="btn btn-primary">Calcular</button>
          <div class="mb-3 form-check">
            <label> <?= $rpta == 0 ? '' : "La suma es:" . $rpta; ?> </label>
          </div>
        </form>
      </div>
    </div>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>

</html>